// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkmJw2uDd29PKPO35hUZKrcFVlS0vU_XY',
    appId: '1:870118729163:web:deb385bb3f01176d6cc24e',
    messagingSenderId: '870118729163',
    projectId: 'ebook-caaf6',
    authDomain: 'ebook-caaf6.firebaseapp.com',
    storageBucket: 'ebook-caaf6.appspot.com',
    measurementId: 'G-MH2091CVT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5Hz0u-_87i5ryR2DdoayZ8LHlK101gb8',
    appId: '1:870118729163:android:8183463623a410b36cc24e',
    messagingSenderId: '870118729163',
    projectId: 'ebook-caaf6',
    storageBucket: 'ebook-caaf6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlSMGTZnlqbD4BduUpb0rUZJ9Tzxixtto',
    appId: '1:870118729163:ios:4ed0fed4bfb1b2256cc24e',
    messagingSenderId: '870118729163',
    projectId: 'ebook-caaf6',
    storageBucket: 'ebook-caaf6.appspot.com',
    iosClientId: '870118729163-r8pkvmfclh664nrvluoprg10vd8gl47g.apps.googleusercontent.com',
    iosBundleId: 'com.example.eBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlSMGTZnlqbD4BduUpb0rUZJ9Tzxixtto',
    appId: '1:870118729163:ios:4ed0fed4bfb1b2256cc24e',
    messagingSenderId: '870118729163',
    projectId: 'ebook-caaf6',
    storageBucket: 'ebook-caaf6.appspot.com',
    iosClientId: '870118729163-r8pkvmfclh664nrvluoprg10vd8gl47g.apps.googleusercontent.com',
    iosBundleId: 'com.example.eBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkmJw2uDd29PKPO35hUZKrcFVlS0vU_XY',
    appId: '1:870118729163:web:f5fafd8587a6d12b6cc24e',
    messagingSenderId: '870118729163',
    projectId: 'ebook-caaf6',
    authDomain: 'ebook-caaf6.firebaseapp.com',
    storageBucket: 'ebook-caaf6.appspot.com',
    measurementId: 'G-JX6JCB2D0Q',
  );
}
